version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx_cont
    ports:
      - "80:80"  # Access your app at http://localhost
    restart: always
    depends_on:
      - django_app
    networks:
      - notes-app-nw
    volumes:
      - static_volume:/app/static  # If Nginx serves static files
      - media_volume:/app/media    # Optional for media files

  django_app:
    build:
      context: .
    image: django_app
    container_name: django_cont
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000
      "
    env_file:
      - ".env"
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - notes-app-nw
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  db:
    image: mysql
    container_name: db_cont
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - notes-app-nw

volumes:
  static_volume:
  media_volume:

networks:
  notes-app-nw:
